import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>MyApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container-fluid px-2 px-md-4 py-5 mx-auto">
        <div className="card card0 border-0">
          <div className="row d-flex">
            <div className="col-lg-5">
              <div className="card1 pb-20 row px-3">
                <div className="row px-3 justify-content-center mt-4 mb-5"> 
                  <div id="carouselExampleIndicators" className="carousel slide" data-ride="carousel">
                    <ol className="carousel-indicators">
                      <li data-target="#carouselExampleIndicators" data-slide-to="0" id="li1"></li>
                      <li data-target="#carouselExampleIndicators" data-slide-to="1" id="li2"></li>
                      <li data-target="#carouselExampleIndicators" data-slide-to="2" id="li3" className="active"></li>
                      <li data-target="#carouselExampleIndicators" data-slide-to="3" id="li4"></li>
                      <li data-target="#carouselExampleIndicators" data-slide-to="4" id="li5"></li>
                    </ol>
                    <div className="carousel-inner">
                      <div className="carousel-item card border-0 card-0">
                        <div className="text-center ">
                          <img src="https://www.tigren.com/blog/wp-content/uploads/2019/02/how-to-sell-electronics-online.png"  alt="" className="img-fluid profile-pic"/>
                        </div>
                        <h6 className="font-weight-bold mt-5">Product Name</h6> 
                        
                        <p className="content mt-2 mb-0">Product Details.</p>
                      </div>
                      <div className="carousel-item card border-0  card-0">
                        <div className="text-center">
                          <img src="https://www.tigren.com/blog/wp-content/uploads/2019/02/how-to-sell-electronics-online.png" alt="" className="img-fluid profile-pic"/>
                        </div>
                        <h6 className="font-weight-bold mt-5">Product Name</h6> 
                        
                        <p className="content mt-2 mb-0">Product Details.</p>
                      </div>
                      <div className="carousel-item active card border-0 card-0">
                        <div className="text-center">
                          <img src="https://www.tigren.com/blog/wp-content/uploads/2019/02/how-to-sell-electronics-online.png"  alt="" className="img-fluid profile-pic"/>
                        </div>
                        <h6 className="font-weight-bold mt-5">Product Name</h6> 
                        
                        <p className="content mt-2 mb-0">Product Details.</p>
                      </div>
                      <div className="carousel-item card border-0 card-0">
                        <div className="text-center">
                          <img src="https://www.tigren.com/blog/wp-content/uploads/2019/02/how-to-sell-electronics-online.png"  alt="" className="img-fluid profile-pic"/>
                        </div>
                        <h6 className="font-weight-bold mt-5">Product Name</h6> 
                        
                        <p className="content mt-2 mb-0">Product Details.</p>
                      </div>
                      
                    </div>
                 </div>
               </div>
               
              </div>
            </div>
            <div className="col-lg-7">
              <div className="card2 card  border-0 px-4 px-sm-5 py-5">
                <small className="text-end mb-3"><a href="">Need an Account?</a></small>
                <h3 className="mb-1 px-3">Welcome Back! </h3>
                <div className="row px-3">
                  <label className="mb-0"><h6 className="mb-0 text-sm py-3">Username</h6></label>
                  <input type="text" name="username" placeholder="Username"/>
                </div>
                <div className="row px-3">
                  <label className="mb-0  "><h6 className="mb-0  py-3 text-sm">Password</h6></label>
                  <input type="password" name="password" placeholder="&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;"/>
                </div>

                
                 <div className="form-check">
                   <div className='form-check-checkbox'><input className="form-check-input" type="checkbox" value="" id="flexCheckDefault"/>
                    <label className="form-check-label px-2" >Remember me</label>
                   </div>
                   <div className='form-check-forgetpassword text-end mb-3'><a href="#" >Forgot Password?</a></div>
                   
                  </div>
                 
                <div className="row mb-4">
                  <div className="offsercol-lg-10">
                    <button className="btn1 text-center mb-1 py-2">Sign in</button>
                  </div>
                </div>

                <div className="line-or">
                  <div className="line"></div>
                  <small className=" text-center">OR</small>
                  <div className="line"></div>
                </div>

                <div className="row text-center">
                  <div className="col-sm-6">
                    <p className="social-connect"><span className="bi bi-facebook"></span><small className="pl-3 pr-1">facebook</small></p>
                  </div>
                  <div className="col-sm-6">
                    <p className="social-connect"><span className="bi bi-google"></span><small className="pl-3 pr-1"> Google</small></p>
                  </div>
                </div>
              </div>
            </div>
         </div>
        </div>
     </div>
    </div>
  )
}
